# Generated by Django 6.0.1 on 2026-02-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_travelpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=10)),
                ('station_name', models.CharField(max_length=100)),
                ('route_number', models.IntegerField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('halt_time', models.IntegerField(blank=True, null=True)),
                ('distance', models.IntegerField()),
                ('day', models.IntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='train.train')),
            ],
            options={
                'ordering': ['route_number'],
            },
        ),
    ]
