# Generated by Django 6.0.1 on 2026-02-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_trainschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainschedule',
            old_name='day',
            new_name='day_number',
        ),
        migrations.RenameField(
            model_name='trainschedule',
            old_name='halt_time',
            new_name='halt_minutes',
        ),
    ]
