# Generated by Django 6.0.1 on 2026-02-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_rename_day_trainschedule_day_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stations/')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hours', models.CharField(default='Open - 24 Hours', max_length=100)),
            ],
        ),
    ]
